### ISSUE TITLE
Changing LinkedVariables when this is not allowed anymore

### ISSUE THREAD

**Issue by bnaudts** [e2immu/e2immu#54]
Source: JFocus TestExpandParameters1.

Stack trace:
Variable io.codelaser.jfocus.standardize.analyzer.example.ExpandParameters_1.same1(io.codelaser.jfocus.standardize.analyzer.example.ExpandParameters_1.R):0:input: not allowed to change LVs anymore: old: f:4, new 
java.lang.IllegalStateException: Variable io.codelaser.jfocus.standardize.analyzer.example.ExpandParameters_1.same1(io.codelaser.jfocus.standardize.analyzer.example.ExpandParameters_1.R):0:input: not allowed to change LVs anymore: old: f:4, new 
	at org.e2immu.analyser.analyser.nonanalyserimpl.VariableInfoImpl.setLinkedVariables(VariableInfoImpl.java:257)
	at org.e2immu.analyser.analyser.nonanalyserimpl.VariableInfoContainerImpl.setLinkedVariables(VariableInfoContainerImpl.java:320)
	at org.e2immu.analyser.analyser.ComputeLinkedVariables.writeLinkedVariables(ComputeLinkedVariables.java:482)
	at org.e2immu.analyser.analyser.ComputeLinkedVariables.writeClusteredLinkedVariables(ComputeLinkedVariables.java:450)
	at org.e2immu.analyser.analyser.statementanalyser.SAApply.contextProperties(SAApply.java:766)

**Comment by bnaudts** [comment]
Solved by introducing a formalObjectType() method in Expression, implemented by InlinedMethod and Lambda, to ensure consistency in the decision of .isMyself()
